AllCops:
  NewCops: enable
  Exclude:
    - "apps/opal_node/node_modules/**/*"
    - "apps/opal_node/build/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

require:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-rails
  - rubocop-sequel

plugins:
  - rubocop-rake

Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Rails:
  Include:
    - "apps/rails/**/*"

Style/Documentation:
  Enabled: false
