# frozen_string_literal: true

eval_gemfile "../Gemfile"

# gem "rails"


gem "rake", "~> 13.2"
gem "sinatra"
gem "rackup"
gem "rack-unreloader"
gem "puma"
gem 'slim'
group :test do
  gem 'test-unit'
  gem "rack-test"
end