# frozen_string_literal: true

eval_gemfile "../Gemfile"

gem "rake", "~> 13.2"
gem "sinatra", "~> 4.1"
gem "puma", "~> 6.5"

group :app do
  gem "rack-unreloader", "~> 2.1"
  gem "rackup", "~> 2.2"
  gem "slim", "~> 5.2"
end

group :database do
  gem "sequel", "~> 5.89"
  gem "sqlite3", "~> 2.5"
end

group :test do
  gem "launchy", "~> 3.1"
end
gem "nio4r", "~> 2.7"
