name: Run test suite

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.4.2' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # Runs 'bundle install' and caches installed gems automatically

      - name: Run tests
        run: bundle exec rake

      - name: Cache test coverage results
        uses: actions/cache@v4
        with:
          path: doc/coverage
          key: test-coverage-${{ github.run_id }}
          restore-keys: |
            test-coverage-

  build-docs:
    runs-on: ubuntu-latest
    needs: test  # ✅ Ensure `test` completes first
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore Gem cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.2'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Restore test coverage cache
        uses: actions/cache@v4
        with:
          path: doc/coverage
          key: test-coverage-${{ github.run_id }}
          restore-keys: |
            test-coverage-

      - name: Build Docs
        run: bundle exec rake build_docs

      - name: Cache generated documentation
        uses: actions/cache@v4
        with:
          path: doc
          key: build-docs-${{ github.run_id }}
          restore-keys: |
            build-docs-

  deploy_pages:
    runs-on: ubuntu-latest
    needs: build-docs  # ✅ Ensure `build-docs` completes first
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore documentation cache
        uses: actions/cache@v4
        with:
          path: doc
          key: build-docs-${{ github.run_id }}
          restore-keys: |
            build-docs-

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          publish_branch: gh-pages
          force_orphan: true
