name: Build and Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build-deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Build Docs
        run: bundle exec rake build_docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          publish_branch: gh-pages
          force_orphan: true
