name: Build and Deploy Docs
on:
  workflow_run:
    workflows: ["Run test suite"]
    branches: [main]
    types:
      - completed
permissions:
  actions: read
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Not building docs, tests failed'
  on-success:
