name: Build and Deploy Docs
on:
  workflow_run:
    workflows: ["Run test suite"]
    branches: [main]
    types:
      - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Not building docs, tests failed'
  on-success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Build Docs
        run: bundle exec rake build_docs

      - name: Download coverage docs
        uses: actions/download-artifact@v4
        with:
          name: test-coverage
          path: doc/coverage
          github-token: ${{ secrets.GH_PAT }}
          merge-multiple: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
          publish_branch: gh-pages
          force_orphan: true
